### ISSUE TITLE
Make a Casdoor starter kit for SpringBoot users

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-spring-boot-starter#1]
Maybe this will be similar to: https://github.com/jcasbin/casbin-spring-boot-starter

A SpringBoot project can easily integrate with Casdoor authentication by using this project. The difference between this project (casdoor-spring-boot-starter) and https://github.com/casdoor/casdoor-java-sdk is that casdoor-java-sdk is a general-purpose SDK for all Java projects. But casdoor-spring-boot-starter is tailored for Java SpringBoot projects only. So it's easier to use. Ideally, casdoor-spring-boot-starter will be built based on casdoor-java-sdk.

Finally we will create a SpringBoot example project to test this repo (casdoor-spring-boot-starter).

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by hsluoyz** [comment]
@tangyang9464 next plz add the README

**Comment by tangyang9464** [comment]
> @tangyang9464 next plz add the README

OK
