### ISSUE TITLE
when i use the vue and springboot , how should i edit the web application whitch on the casdoor and the yaml whitch on the springboot

### ISSUE THREAD

**Issue by qiuyejianweinuan** [casdoor/casdoor-spring-boot-starter#28]
and i meet the problem that i can't resolve it 

org.casbin.casdoor.exception.CasdoorAuthException: Cannot verify signature.
	at org.casbin.casdoor.service.CasdoorAuthService.parseJwtToken(CasdoorAuthService.java:96)

**Comment by hsluoyz** [comment]
@RanTao123

**Comment by hsluoyz** [comment]
@qiuyejianweinuan fixed by SDK: https://github.com/casdoor/casdoor-java-sdk/pull/53 and this repo: https://github.com/casdoor/casdoor-spring-boot-starter/pull/33

Plz use latest `v1.18.0` to resolve this issue
