### ISSUE TITLE
The version of casdoor-java-sdk is 1.16.0, and when logging in, it directly throws an error: org.casbin.casdoor.exception.CasdoorAuthException: Access token not found in JWT payload.

### ISSUE THREAD

**Issue by luguangdong** [casdoor/casdoor-spring-boot-starter#36]
Using casdoor-spring-boot-starter tag v1.8.0, the version of casdoor-java-sdk is 1.16.0, and when logging in, it directly throws an error: org.casbin.casdoor.exception.CasdoorAuthException: Access token not found in JWT payload.

![image](https://github.com/casdoor/casdoor-spring-boot-starter/assets/41789844/236b7eb9-7eea-4f1e-95dd-64834624f097)

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor-spring-boot-starter/commit/80f8c8c99d1f6742b9f1ca2fa95382c4ba54dd0e
