### ISSUE TITLE
springboot sdk uses java sdk version is too low, many functions are not implemented, I hope it can be updated

### ISSUE THREAD

**Issue by Ryan-Kevin** [casdoor/casdoor-spring-boot-starter#38]
springboot sdk uses java sdk version is too low, many functions are not implemented, I hope it can be updated

**Comment by hsluoyz** [comment]
@Ryan-Kevin fixed in: https://github.com/casdoor/casdoor-spring-boot-starter/releases/tag/v1.10.0
