### ISSUE TITLE
Update latest java version in the springboot

### ISSUE THREAD

**Issue by gurujerseyno7** [casdoor/casdoor-spring-boot-starter#49]
Could you please update the Casdoor Java SDK to version 1.34.0 in our Spring Boot project. The current setup is pointing to the older version, 1.33.0 @hsluoyz @jakiuncle  @casbin-bot

**Comment by gurujerseyno7** [comment]
@hsluoyz  Could you please update the JAVA SDK new version in the springboot pom.xm file.

**Comment by hsluoyz** [comment]
@gurujerseyno7 I don't have time to do that all the time. Why not yourself or let your colleague make a qualified PR (pass all CIs)?

**Comment by hsluoyz** [comment]
Done by: https://github.com/casdoor/casdoor-spring-boot-starter/pull/51
